#!/bin/sh

opt_search=false
opt_get=false
opt_download=false
opt_json=false
query=''
getid=''

main() {
	parsed_args=$(getopt -o s:g:djh -l search:,get:,download,json,help -n 'haxmaps' -- "$@")
	getopt_exit_code=$?

	if [ $getopt_exit_code -ne 0  ] ; then
		exit 1
	fi

	eval set -- "$parsed_args" 

	while :; do
		case "$1" in
			-h | --help ) show_help; exit 1 ;;
			-s | --search ) opt_search=true; query="$2"; shift 2 ;;
			-d | --download ) opt_download=true; shift ;;
			-j | --json ) opt_json=true; shift ;;
			-g | --get ) opt_get=true; getid="$2"; shift 2 ;;
			-- ) shift; break ;;
			* ) break ;;
		esac
	done

	if ! $opt_search && ! $opt_get ; then
		show_help
		exit 1
	fi

	if $opt_get ; then
		[ "$getid" -eq "$getid" ] 2>/dev/null ||
			die 'invalid id'

		download "$getid" > "$getid.hbs"
		exit 0
	fi

	if $opt_search ; then
		if $opt_download ; then
			search "$query" | jq --raw-output '.results[].id' | (
				while read -r id; do
					download "$id" > "$id.hbs"
				done
			)
		elif $opt_json ; then
			search "$query"
		else
			printf "%s\t\t%s\n" "ID" "Map name"
			search "$query" | jq --raw-output '.results[] | "\(.id)\t\t\(.name)" '
		fi
		exit 0
	fi

	show_help
	exit 1
}

die() {
	printf "haxmaps: %s\n" "$@" >&2
	exit 1
}

show_help() {
	echo Usage: haxmaps [ -h ] [ [ -jd ] -s search_query ] [ -g haxmap_id ]
	echo Options are:
	echo '     -s | --search                  search in the map database and show the results in readable format'
	echo '     -g | --get                     download a specific map by id'
	echo '     -d | --download                use with the search flag to download all the maps'
	echo '     -j | --json                    use with the search flag to set the output format to json'
	echo '     -h | --help                    display this message and exit'
}

download() {
	curl -s "https://haxmaps.com/dl/$1"
}

search() {
	results=$(curl -s --data-urlencode "queryString=$1" https://haxmaps.com/hb/rpc | grep -Po '<li.*?</li>')
	
	if [ "${#results}" -lt 5 ] ; then
		echo '{ "results": [] }'
		exit 0
	fi

	length=$(echo "$results" | wc -l)

	echo "$results" | (
		index=0
		printf "%s" '{ "results": ['
		while read -r line; do
			map_id=$(echo "$line" | grep -Po 'https://haxmaps.com/map/\K[0-9]+')
			map_name=$(echo "$line" | grep -Po '</b>\K.*?(?=</li>)' | xargs)
			printf "%s" "{ \"name\": \"$map_name\", \"id\": \"$map_id\" }"
			if [ $index -ne $((length-1)) ] ; then
				printf "%s" ','
			fi
			index=$((index+1))
		done;
		printf "%s" ']}'
	)
}

main "$@"
