.Dd August 12, 2022
.Dt HAXMAPS 1
.Sh NAME
.Nm haxmaps
.Nd download and search haxball maps from https://www.haxmaps.com
.Sh SYNOPSIS
.Nm
.Op Fl dhj
.Op Fl s Ar query
.Op Fl g Ar id
.Sh DESCRIPTION
The
.Nm
utility lets you download and search haxball maps.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl d
use with the search flag to download all the maps
.It Fl h
show usage
.It Fl j
use with the search flag to set the output format to json
.It Fl s
search in the map database and show the results in readable format
.It Fl g
download a specific map by id
.El
.Sh EXAMPLES
.Bl -tag -width indent
.It search for futsal maps
haxmaps -s futsal
.It download a map by id
haxmaps -g 938
.El
.Sh SEE ALSO
.Xr haxip 1
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/haxmaps/issues
